# MCUboot child-image Kconfig (merged with MCUboot defaults).
CONFIG_BOOT_SIGNATURE_TYPE_ECDSA_P256=y
# Override the default NCS key with our project key.
# This path is relative to the MCUboot source root (bootloader/mcuboot).
CONFIG_BOOT_SIGNATURE_KEY_FILE="D:/Secure_AB_OTA_Bootloader/app/keys/mcuboot.pem"

CONFIG_LOG=y
CONFIG_MCUBOOT_LOG_LEVEL_INF=y
CONFIG_USE_SEGGER_RTT=n
CONFIG_RTT_CONSOLE=n
CONFIG_UART_CONSOLE=y
CONFIG_LOG_BACKEND_UART=y
CONFIG_LOG_BACKEND_RTT=n
